---

- name: Create the Systemd Unit file for the phpfpm-exporter service
  template:
    src: phpfpm_exporter.systemd.j2
    dest: /etc/systemd/system/phpfpm_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd and restart phpfpm_exporter
  when: ansible_service_mgr == "systemd"

- name: Create the Upstart Unit file for the phpfpm-exporter service
  template:
    src: phpfpm_exporter.upstart.j2
    dest: /etc/init/phpfpm_exporter.conf
    owner: root
    group: root
    mode: 0644
  notify: restart phpfpm_exporter
  when: ansible_service_mgr == "upstart"

- name: Create the generic start-stop script for the phpfpm-exporter service
  template:
    src: phpfpm_exporter.service.j2
    dest: /etc/init.d/phpfpm_exporter
    owner: root
    group: root
    mode: 0755
  notify: restart phpfpm_exporter
  when: ansible_service_mgr not in [ "systemd", "upstart" ]
