---

- name: Set the Github API endpoint
  set_fact:
    _phpfpm_exporter_github_api_url: |-
      {% if phpfpm_exporter_release_tag == 'latest' %}
      https://api.github.com/repos/hipages/php-fpm_exporter/releases/latest
      {% else %}
      https://api.github.com/repos/hipages/php-fpm_exporter/releases/tags/{{ phpfpm_exporter_release_tag }}
      {% endif %}

- name: Set the Github API token
  set_fact:
    _phpfpm_exporter_github_api_token: "{{ lookup('env', 'GITHUB_API_TOKEN') }}"

- name: Fetch the phpfpm-exporter release information from Github
  uri:
    url: "{{ _phpfpm_exporter_github_api_url }}"
    method: GET
    headers:
      Authorization: "{% if _phpfpm_exporter_github_api_token %}token {{ _phpfpm_exporter_github_api_token }}{% endif %}"
  check_mode: no
  register: _phpfpm_exporter_github_release
  until: |
    'status' in _phpfpm_exporter_github_release
      and _phpfpm_exporter_github_release['status'] == 200
  retries: 5
  delay: 15

- name: Get the tag of the latest phpfpm-exporter Github release
  set_fact:
    phpfpm_exporter_release_tag: "{{ _phpfpm_exporter_github_release['json'] | json_query('tag_name') }}"
  when: phpfpm_exporter_release_tag == "latest"

- debug:
    msg: "Json {{ _phpfpm_exporter_github_release['json'] }}"

- debug:
    msg: "Tag {{ phpfpm_exporter_release_tag }}"

- name: Set the Github download URL for the phpfpm-exporter release
  set_fact:
    phpfpm_exporter_release_url: "{{ _phpfpm_exporter_github_release['json'] | json_query(_phpfpm_exporter_release_asset_url_query) }}"
  vars:
    _phpfpm_exporter_release_asset_url_query: "assets[?name=='{{ hostvars[inventory_hostname] | phpfpm_exporter_release_build(phpfpm_exporter_release_tag) }}.tar.gz'] | [0].browser_download_url"  # noqa 204

- debug:
    msg: "URL {{ phpfpm_exporter_release_url }}"
